### ISSUE TITLE
Add options to customize appearance of welcome message

### ISSUE THREAD

**Issue by realmazharhussain** [realmazharhussain/gdm-settings#106]
Currently following CSS works.

```CSS
.login-dialog-banner {
  color: #FFF;
  font-size: 1.5em;
  font-weight: bold;
  background-color: #40A;
  padding: 10px;
  border-radius: 7px;
}
```

Alpha value in `rgba(r, g, b, a)` is discarded for some reason when used as `background-color`.
